### ISSUE TITLE
Update billing details for contribution link is blank

### ISSUE THREAD

**Issue by jrobens** [agileware/au.com.agileware.ewayrecurring#1]
CiviCRM is currently 4.7.31

eWay_Recurring (au.com.agileware.ewayrecurring) 1.5.2
The template looks like it is loaded from here web/sites/all/modules/civicrm/CRM/Upgrade/4.6.10.msg_template/message_templates/contribution_online_receipt_html.tpl

The %1 link is blank in

You can update billing details for this recurring contribution by <a href="%1">visiting this web page</a>
How do we fix this?

**Comment by agilewarealok** [comment]
@jrobens Thanks for creating and pointing out the issue.

We've fixed it. Would you mind testing it from this patch https://github.com/agileware/au.com.agileware.ewayrecurring/commit/38ae68e5b53844a3a4361d014214ba09ae9507b5 ?

**Comment by jrobens** [comment]
OK - it didn't work. I don't get a receipt sent and no transaction was deducted.

**Comment by jusfreeman** [comment]
@jrobens recommend you contact us directly to provide more details, use https://agileware.com.au/contact
