### ISSUE TITLE
CronJob result is plain html of the front page for recurring eWay_Recurring payment  cron job

### ISSUE THREAD

**Issue by harshal6** [agileware/au.com.agileware.ewayrecurring#13]
/usr/local/bin/php73.cli ~/www/www/wp-content/plugins/civicrm/civicrm/bin/cli.php -u name -p "pass" -e Job -a run_payment_cron --processor_name=eWay_Recurring > /dev/null 2>&1

/usr/local/bin/php73.cli ~/www/www/wp-content/plugins/civicrm/civicrm/bin/cli.php -u name -p "pass" -e Job -a execute

My civicron.sh file has the above code which seems to be calling eWay_Recurring job , everytime it runs the Cron Job Result sent to my email address(as its configured in cpanel) is HTML of my frontpage.
When I check the logs it does not show anything related to cron job, but everytime cron is run, I get the full html.

**Comment by MikeyMJCO** [comment]
The `cli.php` method of running cron on Drupal 8 or 9 should be considered deprecated and unsupported. Even on other CMSes it's not recommended - use `cv` or `drush` (CV is best)
