### ISSUE TITLE
Does this allow for credit card details to be updated by the card owner (contact) via the civicrm interface, eg the Contact Dashboard?

### ISSUE THREAD

**Issue by petednz** [agileware/au.com.agileware.ewayrecurring#22]

**Comment by petednz** [comment]
Via Contact Dashboard I can get to an 'Update Billing Details' link on my recurring contribution

but clicking that offers me 

![image](https://user-images.githubusercontent.com/5800574/152466439-1517a3bb-03d8-4e7a-ba4f-a0ed8b835857.png)

which is problematic as

a/ i do have a card 'on record' and 

b/  the add credit card does not function and

c/ not sure if c/ is a problem yet ie "Please be sure to click RETURN TO MERCHANT after adding a credit card" may make sense if b/ works

By 'i do have a card on record' i meant that if i went to my contact record and add new credit card payment under 'stored credit card' i see details for two cards

**Comment by petednz** [comment]
Bit more info and the rubber duck is still nodding away.

eway ext'n v: 2.3.17
civi 5.40.2

Via the link from Contact Dashboard I go to either

/civicrm/contribute/updatebilling?reset=1&crid=2317

Via the Change Billing Details on my active recurring list on my Contribution tab if I click EDIT I go to

/civicrm/contribute/updatebilling?reset=1&crid=2317&cid=40184&context=contribution

 and I see and can switch between my Stored Credit Cards

so is the problem simply that the link on my Contact Dashboard is incomplete and needs the Contact ID appending

(i understand this may be a core issue, not specific to this extension, and have also asked on Chat but i don't have other processors that offer stored cards so not able to compare)

**Comment by agileware-justin** [comment]
FYI, I've tasked this to be reviewed at some stage in the coming weeks.

Agileware Ref: CIVIEWAY-225

**Comment by petednz** [comment]
Just an update. My testing is showing that I can add a Card, and having added it i can then select it. but the UI is really wonky in that the first screen shows 'no cards found'
![image](https://user-images.githubusercontent.com/5800574/155420054-46fc526c-5ecd-4713-8465-b3b786e1dbba.png)
when I click Add Credit Card i get whisked off to eway. on my return i then see both my new card and old cards listed on that field, so i can then select my new card and Save
i then get returned to the dashboard where I again do not see my cards. ( i will try to grab more screenshots when i try this again, but running out of credit cards to try and not sure what happens if i try to add an already stored card (which i might try doing since i don't get shown my list of cards))

**Comment by agileware-justin** [comment]
Sorry @petednz we don't have any time to work on this one at this stage. So if you want to submit a PR then go for it.
