### ISSUE TITLE
Recurrings that fail still have their next payment date pushed out to the next cycle

### ISSUE THREAD

**Issue by petednz** [agileware/au.com.agileware.ewayrecurring#24]
per https://chat.civicrm.org/civicrm/pl/3ro58imtqpf3dnu1jdu35zotca

when the first 'attempt' to charge the card happens the next_scheduled_date is jumped forward by the relevant cycle even if the payment isn't successful. the processor then lets civi know it was a fail, and tries again, etc, etc and reports each fail till it gives up.

but meanwhile the next_scheduled_date is showing as 'next year', which means a bunch of reports etc get screwed up. Not hard to adjust them but it didn't make sense to me to have the 'next payment' date pushed out 'immediately' rather than waiting for a payment to succeed

and this also affects memberships, ie if the payment fails 3 times (or whatever the limit is) the associated membership seems to be still showing as auto-renew even though this has just failed its max times

Eileen commented that this might have been done to avoid double payments but 'we' now usually use the status to do that (there is a status 'Processing' intended for this use)

**Comment by agileware-justin** [comment]
It looks like this situation is specifically handled by this part of the code

https://github.com/agileware/au.com.agileware.ewayrecurring/blob/1aab7df62611f41ab5c8d5beca0d70bc54765a71/eWAYRecurring.process.inc#L107

**Comment by agileware-justin** [comment]
I'm going to mark this as closed since we have not been able reproduce this issue. If you can provide reproduction steps that would help with any investigation. Have a great day! :smile:
