### ISSUE TITLE
Sending receipts for each recurring payment

### ISSUE THREAD

**Issue by petednz** [agileware/au.com.agileware.ewayrecurring#26]
Hi Justin - any opinion about this. we have a customisation for this but @konadave says there were a couple of places in eWay where is_email_receipt is explicitly set to FALSE/0, and setting it to TRUE/1 might be all it would take, and that presumably we could also add a setting for it on the settings form for eWay.

any thoughts? would you agree this is a valid solution and would you accept a PR?

**Comment by agileware-justin** [comment]
It's a bit light on detail. What's the problem exactly? And what's the other conversation?

**Comment by agileware-justin** [comment]
In test of PRs if you're changing the default behaviour, then provide a setting and leave the current behaviour as default, with option to change it.

**Comment by petednz** [comment]
My understanding is that CiviCRM does not send out a receipt for each recurring Contribution.

Is my understanding incorrect? Or if it is correct, would it make sense to address it within your extension for eWay users

**Comment by petednz** [comment]
The reference to Dave Reedy (konadave) relates to conversations in Fuzion's ticket system. He has been working on this issue for u.

**Comment by petednz** [comment]
and I wanted to introduce him in case you do ok a PR and it comes from someone (Dave) who you are not familiar with.

**Comment by agileware-justin** [comment]
We're happy to receive PRs from random unknown people.

My view is that if someone is willing to contribute time, effort and in most cases has been paid to work on a PR. Then the very least we can do is review it and provide feedback. When we do this depends on availability, because as you know we're busy too.

**Comment by agileware-justin** [comment]
@petednz EWAY will send a receipt out everytime. CiviCRM receipting is disabled. So if you want this changed, then the PR should provide a EWAY Setting and leave the current behaviour as default, with option to enable CiviCRM sending receipts.

Customer feedback was that they did not want CiviCRM to send receipts for recurring payments and the EWAY receipt was sufficient. So we do not want to change this default behaviour, hence my advise above.

And now you get a Agileware Ref: CIVIEWAY-237

**Comment by petednz** [comment]
i think the issue client was having, is the have Tax 'on' and hence expect a PDF invoice to go out. which obviously eway can't do

**Comment by agileware-justin** [comment]
Some would also argue that CiviCRM can't send a valid Tax invoice too! :smile:

**Comment by agileware-fj** [comment]
Fixed in PR #27
