### ISSUE TITLE
Latest version 2.4.1 breaks the site

### ISSUE THREAD

**Issue by jitendrapurohit** [agileware/au.com.agileware.ewayrecurring#30]
Looks like the civix upgrade hasn't completed correctly. Updating this extension to latest 2.4.1 version breaks the site -

>Fatal error: Cannot redeclare eWAYRecurring_civicrm_entityTypes() (previously declared in .../web/sites/default/civicrm/extensions/au.com.agileware.ewayrecurring/eWAYRecurring.php:301) in .../web/sites/default/civicrm/extensions/au.com.agileware.ewayrecurring/eWAYRecurring.php on line 561

If we remove eWAYRecurring_civicrm_entityTypes, there are other function errors like -

>Error: Call to undefined function _ewayrecurring_civix_civicrm_xmlMenu() in ewayrecurring_civicrm_xmlMenu() (line 25 of /.../web/sites/default/civicrm/extensions/au.com.agileware.ewayrecurring/eWAYRecurring.php).
>PHP Fatal error:  Uncaught Error: Call to undefined function _ewayrecurring_civix_civicrm_alterSettingsFolders() in /.../web/sites/default/civicrm/extensions/au.com.agileware.ewayrecurring/eWAYRecurring.php:291

>Error: Call to undefined function _ewayrecurring_civix_civicrm_managed() in ewayrecurring_civicrm_managed() (line 255 of /.../web/sites/default/civicrm/extensions/au.com.agileware.ewayrecurring/eWAYRecurring.php).

**Comment by agileware-justin** [comment]
Fixed in 2.4.2

**Comment by petednz** [comment]
Thx for the speedy response AgileMan
