### ISSUE TITLE
User deprecated function: Deprecated function CRM_Core_ManagedEntities::get, use api. 

### ISSUE THREAD

**Issue by stesi561** [agileware/au.com.agileware.ewayrecurring#36]
Lots of red error messages :( 

Looks like is coming from here

https://github.com/agileware/au.com.agileware.ewayrecurring/blob/5774d16eb302c1442518af5d11da39462df34723/eWAYRecurring.php#L213

Sorry don't have time to do a full fix right now but looks like this needs something like:

```
$paymentProcessorTypes = \Civi\Api4\PaymentProcessorType::get()
  ->addSelect('id')
  ->addWhere('name', '=', 'eWay_Recurring')
  ->setLimit(25)
  ->execute();
foreach ($paymentProcessorTypes as $paymentProcessorType) {
  // do something
}

```

**Comment by agileware-justin** [comment]
Really need more details Luke, not seeing this issue
