### ISSUE TITLE
Warning after upgrade to wordpress/civicrm 5.72.1 re Deprecation Permission 'view payment tokens'

### ISSUE THREAD

**Issue by gzh1960** [agileware/au.com.agileware.ewayrecurring#41]
Wordpress: 6.5.2 
CiviCRM: 5.72.1 (just upgraded and get the warning below now) 
PHP: 8.1
MySQL: 8
eWay Recurring Payment Processor extension: 2.6.6

**Warning error on any CiviCRM screen:**

Deprecated: Permission 'view payment tokens' should be declared with 'label' and 'description' keys. See https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_permission/ Caller: CRM_Core_Permission::assembleBasicPermissions in mywebsite/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php on line 1129

Deprecated: Permission 'edit payment tokens' should be declared with 'label' and 'description' keys. See https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_permission/ Caller: CRM_Core_Permission::assembleBasicPermissions in mywebsite/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php on line 1129

Can anybody help me with this warning. It leads to 2 x warnings being displayed on every page displayed. Also I noticed that when I went to check the eWay payment processor CiviCRM would NOT display the configured record. Note: Once I commented out the line 1129 as per above it would display the eWay record. Have tested a live donation with the commented out code and it works currently.

Thanks in advance for your help.

**Comment by pradpnayak** [comment]
PR at https://github.com/agileware/au.com.agileware.ewayrecurring/pull/42

**Comment by agileware-fj** [comment]
@pradpnayak's PR should prevent the line in question from being reached
