### ISSUE TITLE
Recurring not taking recurring payment

### ISSUE THREAD

**Issue by Wyntery** [agileware/au.com.agileware.ewayrecurring#5]
I have installed and configured eWay recurring on my CiviCRM Wordpress site. The CRON jobs are running for the eWay Recurring Payments and eWay Transaction Verification jobs. Users make the initial payment OK when selecting the recurring option, however the subsequent payments are not being taken. The payment cycle is every 7 days. What should I be looking for to find out what is going wrong? I have fairly basic skills.

**Comment by agileware-fj** [comment]
If there are issues with actually communicating with eWAY, you should still have contributions created, put they will be marked as failed or pending (incomplete transaction).  Additionally, information about failing transactions will be shown in the CiviCRM log file.

If you are not seeing failed contributions, this is more likely to be an error with scheduling itself. Check the parameters of your recurring contributions - specifically that the next scheduled transaction date is set as you expect.

**Comment by agileware-justin** [comment]
@Wyntery if you are still stuck and need support then contact us directly for paid support, https://agileware.com.au/contact

Marking this issue as closed as this functionality is working and appears to be a configuration issue in your environment.
