### ISSUE TITLE
Replace calls to errorExit with throwing Processor Exception

### ISSUE THREAD

**Issue by eileenmcnaughton** [agileware/au.com.agileware.ewayrecurring#6]
ie https://github.com/agileware/au.com.agileware.ewayrecurring/blob/master/au_com_agileware_ewayrecurring.class.php#L624

and

https://lab.civicrm.org/dev/financial/-/issues/131

(It's pretty trivial to do - e.g https://lab.civicrm.org/dev/core/-/commit/c0bac359f666619465181d2f526d5f9b8748beb4 
 )

**Comment by agileware-justin** [comment]
@eileenmcnaughton can you submit a PR?

**Comment by eileenmcnaughton** [comment]
I'm just logging tickets against various processors using deprecated practices - we've added deprecation notices in core now = I have fixed the ones in core but can't do all the non-core ones

**Comment by agileware-justin** [comment]
Agileware Ref: CIVIEWAY-195

**Comment by agileware-pengyi** [comment]
https://github.com/agileware/au.com.agileware.ewayrecurring/commit/bec4d6182380419714fcae32ac9de81d8c66452f

**Comment by agileware-pengyi** [comment]
close
