### ISSUE TITLE
Deprecated: Non-static method CRM_eWAYRecurring_eWAYRecurringUtils::getCustomerTokenFromResponse() should not be called statically 

### ISSUE THREAD

**Issue by harshal6** [agileware/au.com.agileware.ewayrecurring#9]
My extension version 2.2.12 .
I suggest we should fix this in latest version as well.
Should we use $this->getCustomerTokenFromResponse() ?

**Comment by agileware-justin** [comment]
Agileware Ref: CIVIEWAY-196

**Comment by agileware-pengyi** [comment]
https://github.com/agileware/au.com.agileware.ewayrecurring/commit/3da6f5ff17d651016c2b854c8c40293a1c4b5ebb
The issue should be fixed in this branch. @harshal6 it would be great if you can test this.

**Comment by agileware-pengyi** [comment]
close
